### ISSUE TITLE
Implement hipGetErrorString

### ISSUE THREAD

**Issue by bensander** [GPUOpen-ProfessionalCompute-Tools/HIP#1]
[thanks! updated to hipGetErrorString]
Currently hipGetErrorString returns the name of the error (ie "hipErrorInvalidDevice") but really should return a full message string explaining the error.

Reference:
See src/hip_hcc.cpp for implemention of hipGetErrorString function.
See include/hip_runtime_api.h for a doxygen-format comments that explain each error.- these could form the text of the error-string message set by this function.

**Comment by sutt0n** [comment]
For future references and to avoid confusion, I believe that `hipErrorString` (what you've typed above as of now) should be `hipGetErrorString`.

**Comment by adityaatluri** [comment]
Supported here: https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/developer-preview/src/hip_error.cpp
Closing issue
