### ISSUE TITLE
hipLaunchKernel alone does not work

### ISSUE THREAD

**Issue by nhaustov** [GPUOpen-ProfessionalCompute-Tools/HIP#11]
The following simple test fails with no device found.
a.out: /srv/git/HIP/src/hip_hcc.cpp:1019: ihipDevice_t *ihipGetTlsDefaultDevice(): Assertion `ihipIsValidDevice(tls_defaultDevice)' failed.
Aborted (core dumped)

Adding some other code, for example:
  void* mem;
  hipMalloc(&mem, 1024);
to the beginnig makes it work. The problem seems to be that hipLaunchKernel does not initialize HIP runtime.

#include "hip_runtime.h"

__global__ void empty_hip_kernel(hipLaunchParm lp, int param)
{
}

int main(int argc, const char** argv)
{
  hipLaunchKernel(HIP_KERNEL_NAME(empty_hip_kernel), dim3(1), dim3(1), 0, 0, 0);
  hipDeviceSynchronize();
  return 0;
}

**Comment by adityaatluri** [comment]
Hi Nikolay,
Thanks. Working on it

**Comment by adityaatluri** [comment]
I have updated in the staging build.

**Comment by bensander** [comment]
thanks Aditya - looks good.
