### ISSUE TITLE
Hip error

### ISSUE THREAD

**Issue by trinayan** [GPUOpen-ProfessionalCompute-Tools/HIP#16]
I just cloned this repo. The previous versions were working but now I get an error that it requires a different version of HCC. However the HCC link given in the github page for HIP has deb/tar packages that were last updated in January. Could anyone please point me to a recent package of HCC because the ones there are outdated and I cannot find a newer version. As a result my HIP is not running. Please help.

**Comment by mattmacy** [comment]
If you look a bit further it explains how to  clone and build the hcc sources. If you can't find it I'll dig it up again. I built the new hcc compiler myself. I think I could have avoided the need to do so by simply disabling the options that were causing it to complain.


 ---- On Tue, 29 Mar 2016 19:30:23 -0700 trinayan <notifications@github.com> wrote ----

**Comment by trinayan** [comment]
I tried it. But the hcc page I went to in bitbucket was last updated in February. And I still get the same error. Could you please point me towards it?. Also for reinstalling a newer version of hcc do I have to remove my old one or is it just updated?.

**Comment by trinayan** [comment]
I updated the compiler from source. Now the version is HCC clang version 3.5.0  (based on HCC 0.10.16133-a923f05-7e4cd9e LLVM 3.5.0svn) .
However now hipcc shows an error when I try to compile. I cannot understand the errors because they were never there with the older versions of HIP or HCC. I am attaching the screenshot here for your reference. Please help
<img width="1280" alt="screen shot 2016-03-30 at 8 51 04 am" src="https://cloud.githubusercontent.com/assets/9054762/14142593/b590ac3a-f654-11e5-9db9-bdc524becafd.png">

**Comment by adityaatluri** [comment]
Hi,
It seems like your runtime is not the latest one. Checkout the dev branch of ROCR. Before running a HIP app, can you try running HSA sample provided with ROCR package?

**Comment by bensander** [comment]
Right, there were several changes to HIP, HCC, and ROCR which all needed to be carefully coordinated.  We tried to describe these requirements through the compiler warnings or README docs but the coordination can still be somewhat tricky.    Basically you need a new HCC (can build from source or download a binary package), and the DEV branch of the ROCR/ROCK driver stack.

FYI, here are the release notes.  To make this easier in the future we can include links by the notes.

===================================================================================================
Release:0.82.00
Date: 2016.03.07
- Bump minimum required HCC workweek to 16074.
- Bump minimum required ROCK-Kernel-Driver and ROCR-Runtime to Developer Preview 2.
- Enable multi-GPU support.
  * Use hipSetDevice to select a device for subsequent kernel calls and memory allocations.
  * CUDA_VISIBLE_DEVICES / HIP_VISIBLE_DEVICE environment variable selects devices visible to the runtime.
- Support hipStreams – send sequences of copy and kernel commands to a device.
  * Asynchronous copies supported.
- Optimize memory copy operations.
- Support hipPointerGetAttribute – can determine if a pointer is host or device.
- Enable atomics to local memory.
- Support for LC Direct-To-ISA path.
- Improved free memory reporting.
  * hipMemGetInfo (report full memory used in current process).
  * hipDeviceReset (deletes all memory allocated by current process).


===================================================================================================

**Comment by trinayan** [comment]
So I tried updating the ROCR with the dev branch package. Now I am getting an error when I try to run the ROCR samples located in /opt/hsa/sample . Its a relocation error. If I roll back to my old version I dont have the issue. But with this one i get the error. I am attaching the screenshot for your reference. 
<img width="1280" alt="screen shot 2016-03-30 at 2 52 20 pm" src="https://cloud.githubusercontent.com/assets/9054762/14153808/5a335ff8-f687-11e5-8a02-9bc6e375ddb0.png">

**Comment by adityaatluri** [comment]
Hi,
The issue is with your thunk library. Try installing it from ROCK/packages/ubuntu. The file name is libhsakmt.deb

**Comment by trinayan** [comment]
Ok. Do I need to reinstall entire drivers again?.

**Comment by trinayan** [comment]
So now the samples inside /opt/hsa is executed correctly. However when I do the make on the samples folder in HIP I am running into a new error as shown in the screenshot.  Do you know whats the issue?. Thank you
<img width="1280" alt="screen shot 2016-03-30 at 4 53 31 pm" src="https://cloud.githubusercontent.com/assets/9054762/14157269/44d4f430-f698-11e5-92bf-386bd45d23ad.png">

**Comment by trinayan** [comment]
So now hipcc is compiling fine but strangely I have a new issue because i reinstalled the runtime as per the instructions mentioned here. When I go to /opt/hsa/samples and run the code I get the errors shown in the screen.
<img width="1280" alt="screen shot 2016-03-30 at 5 55 06 pm" src="https://cloud.githubusercontent.com/assets/9054762/14158894/bd6df650-f6a0-11e5-820c-ca311166f8f0.png">

**Comment by adityaatluri** [comment]
Ok. Seems like you have been mixing up various parts.
1. Install ROCK. All the debian packages.
2. Install ROCR. Try running hsa sample. If it doesn't work, the problem can be in HSA lib or Thunk. 

For your question posted above, you need to install libhsakmt.deb. Make sure you reboot after this.

**Comment by trinayan** [comment]
Ok I did install ROCK first and then ROCR and have the same Thunk library error. I am confused because when ROCK is installed it has the libhsakmt.deb in it. So if I am still getting the error where should I install it from?.

**Comment by mangupta** [comment]
Sometimes when installing newer ROCK and ROCR packages, the older packages do not get removed. So this is what I usually do to ensure that there are no issues with the way I have installed the packages:
1. Uninstall all ROCK packages (In the case of Ubuntu these would be packages that match: compute-firmware*, libhsakmt*, linux-headers*obsidian*, linux-image*obsidian*, linux-image-extra*obsidian*)
2. Uninstall all ROCR packages (i.e. hsa-runtime -dev)
3. Reboot
4. Install ROCK packages from https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/
5. Install ROCR packages from https://github.com/RadeonOpenCompute/ROCR-Runtime/
6. Reboot
7. Verify that HSA sample works fine.

_**Note:** The thunk version to be installed is dependent on the version of ROCK installed. Hence you should not install the thunk from ROCT since the correct version to be used is already bundled with ROCK packages._

**Comment by trinayan** [comment]
Ok . So I did that and it works now. The samples in /opt/hsa work fine. Now what do I have to do to run the latest HIP version?. Because i still get an error there.
<img width="1280" alt="screen shot 2016-03-31 at 8 18 39 pm" src="https://cloud.githubusercontent.com/assets/9054762/14194567/de6829a6-f77d-11e5-992d-f087ba3511a7.png">

**Comment by adityaatluri** [comment]
Hi,
Did the HSA sample work?

**Comment by trinayan** [comment]
Yes it did

**Comment by adityaatluri** [comment]
Which GPU are you using?

**Comment by trinayan** [comment]
Kaveri machine. I tried the matrix multiplication examples from HSA debugger and that is working fine. It seems an issue with HIP in particular.

**Comment by adityaatluri** [comment]
Hi,
The square app is written with Fiji in mind. You can pass host pointers to kernels on an APU. But still, copying data from host to device should work on APU.

**Comment by trinayan** [comment]
Is it a compiler version issue?.

**Comment by adityaatluri** [comment]
No. It's HIP API + HSA issue. I you want to test compiler, create a file with just kernel and compile with hipcc. It'll show any errors.

**Comment by trinayan** [comment]
But the initial release of HIP was working. So does this mean there is no way to run the current HIP on the kaveri?

**Comment by adityaatluri** [comment]
We can run HIP on Kaveri. I did it myself. I am trying to reproduce the issue on my system

**Comment by trinayan** [comment]
Ok. Please let me know. Thanks very much for your help throughout the last few days.

**Comment by adityaatluri** [comment]
Sure. Not a problem.

**Comment by adityaatluri** [comment]
Hi,
It is working on my kaveri system. I am using all public packages.
Here is what you can do to find where the issue is:
1. Try running other HIP samples.
2. Try running tests in tests/src directory
![screenshot from 2016-04-01 09 07 08](https://cloud.githubusercontent.com/assets/2188479/14209393/957d95fc-f7e9-11e5-9f72-98b743d76e60.png)

**Comment by trinayan** [comment]
So the HIP tests are not running even. Since the error happens when compiling I feel it could be a compiler issue. I am posting the screenshot here. 
<img width="1280" alt="screen shot 2016-04-01 at 4 39 27 pm" src="https://cloud.githubusercontent.com/assets/9054762/14219481/7209c93a-f828-11e5-8824-50d7190653a2.png">

**Comment by bensander** [comment]
It looks like you are trying to compile against an older version of the HSA runtime.   HIPCC looks for this include in $HSA_PATH (or /opt/hsa if HSA_PATH not set).  Make sure that this HSA is the “dev” branch discussed earlier on this issue.

**Comment by trinayan** [comment]
Yes I was previously only installing the dev branch of ROCK. Forgot to install the ROCR dev branch. But now its working. 
Thank you all for being very helpful. One last thing. What flags do i need to pass to hipcc to compile for debug ?. Is the -g flag enough?.

**Comment by bensander** [comment]
Hipcc will pass through all options to HCC (or NVCC) depending on platform.  So –g should give you debug support in your application, ie “square”.

**Comment by trinayan** [comment]
Ok. Fine. Thank you once again to everyone involved  :) . You all have been very helpful over the past few days.
