### ISSUE TITLE
Converting CUDA sample that uses OpenCV to HIP

### ISSUE THREAD

**Issue by briansp2020** [GPUOpen-ProfessionalCompute-Tools/HIP#17]
I'm trying to convert Udacity parallel programming class problem sets to HIP. It uses OpenCV and it looks like it is not compatible with hcc. I reported the problem to hcc project and was told that HIP team may have a solution. Is there a way to use hcc/HIP to compile/link OpenCV proejcts?
See https://github.com/RadeonOpenCompute/hcc/issues/47 for more information.

The issue seems to be that OpenCV requires libstdc++ and hcc requires libc++.

Thanks

**Comment by bensander** [comment]
Hi Brian - thanks for your note.  we'll be releasing a version of hip this week that uses libstdc++ by default on the hcc path.  This will allow programs to use a mixture of code compiled with G++ and HCC, including code which uses C++ standard libraries (vectors, strings) in the interfaces.  You'll need a new HCC along with HIP - actually the HCC changes are already in the HCC master branch.

**Comment by briansp2020** [comment]
@bensander 
Are you going to release new version of HIP soon? ROCm 1.1 seems to still use HIP 0.84 which links to libc++. Or, am I missing something?

**Comment by mangupta** [comment]
Hi Brian,
You should see the update to HIP happening sometime next week.

**Comment by briansp2020** [comment]
The new release seems to work now!

**Comment by bensander** [comment]
Thanks Brian.  So many of our users only comment when it breaks. :)
