### ISSUE TITLE
Incorrect conversion of "warpSize" keyword with hipify

### ISSUE THREAD

**Issue by ekondis** [GPUOpen-ProfessionalCompute-Tools/HIP#18]
Using **hipify** to convert a ".cu" file to a HIP ".cpp" file I noticed that the special variable _warpSize_ within a kernel's code is transformed to _hipWarpSize_. I think it should stay as is (_warpSize_).

**Comment by adityaatluri** [comment]
Hi,
The warpSize between NVIDIA and AMD GPUs are different. Which are 32 for NVIDIA and 64 for AMD. If you take a look at HIP source, `hipWarpSize` is a macro of value 64. HIP automatically translates to platform dependent value during compilation

**Comment by ekondis** [comment]
The problem is that **hipcc** does not recognise _hipWarpSize_. Trying to compile a hipified kernel returns error on _hipWarpSize_:

```
test-hipwarpsize.cpp:8:23: error: use of undeclared identifier 'hipWarpSize'
        g_data[i] = gridSize+hipWarpSize;
                             ^
1 error generated.
Died at /opt/rocm/bin/hipcc line 230.

```

**Comment by adityaatluri** [comment]
@mangupta @bensander any comments?
