### ISSUE TITLE
hipFree returns error code when 0/null-pointer is passed.

### ISSUE THREAD

**Issue by briansp2020** [GPUOpen-ProfessionalCompute-Tools/HIP#20]
I don't know how common the practice is. But Udacity homework code calls cudaFree(0) before doing anything else and hipified version returns error code and cause the program to exit with an error. If this practice is common among CUDA software, hipFree should return success code and make it behave more like cudaFree. In C, calling free with 0/null-pointer does not cause error either.

See line 27 of https://github.com/udacity/cs344/blob/master/Problem%20Sets/Problem%20Set%201/HW1.cpp

**Comment by bensander** [comment]
Yes, calling hipFree with NULL pointer should initialize the runtime but not return an error.  We will fix.

**Comment by mangupta** [comment]
This was fixed in hip 0.90. Calling hipFree(0) now initializes the runtime and returns hipSuccess.
