### ISSUE TITLE
Cannot call __device__ class member from kernel function on HCC platform

### ISSUE THREAD

**Issue by jkelling** [GPUOpen-ProfessionalCompute-Tools/HIP#24]
I am not sure if this issue is a genuine HIP issue or if it originates in HCC. Because I am only using HCC through HIP, I am reporting this here.

$ hipcc --version
> HCC clang version 3.5.0  (based on HCC 0.10.16186-d14f969-7461349 LLVM 3.5.0svn)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix

The following code does not compile:

	#include "hip/hip_runtime.h"
	
	struct Foo
	{
		int m_bar = 5;
	
		__device__ int bar(int a)
		{
			return a+m_bar;
		}
	};
	
	__global__ void kernel(hipLaunchParm lp, int a)
	{
		Foo foo;
		foo.bar(a);
	}
	
	int main()
	{
		hipLaunchKernel(HIP_KERNEL_NAME(kernel), dim3(1), dim3(1), 0, 0, 5);
	
		return 0;
	}

> test_direct.cpp:16:6: error:  'Foo::bar': no overloaded function has restriction specifiers that are compatible with the ambient context 'kernel'
So, it looks like the compiler either thinks, that foo.bar is not a `__device__` function, or it mistakes the kernel for a host function.

Strangely, calling a non-member `__device__` function, which in turn calls the member works. So the following code compiles:
	
	#include "hip/hip_runtime.h"
	
	struct Foo
	{
		int m_bar = 5;
	
		__device__ int bar(int a)
		{
			return a+m_bar;
		}
	};
	
	__device__ int bar_wrapper(Foo& foo, int a)
	{
		return foo.bar(a);
	}
	
	__global__ void kernel(hipLaunchParm lp, int a)
	{
		Foo foo;
		bar_wrapper(foo, a);
	}
	
	int main()
	{
		hipLaunchKernel(HIP_KERNEL_NAME(kernel), dim3(1), dim3(1), 0, 0, 5);
	
		return 0;
	}

**Comment by bensander** [comment]
Hi - we are looking at this.  it does appear to be an issue with HCC.

**Comment by briansp2020** [comment]
One of the Parboil bench has this type of code also.

**Comment by scchan** [comment]
We have a fix for this in hcc:
https://github.com/RadeonOpenCompute/hcc-clang/pull/3
