### ISSUE TITLE
Use logic-defined or in hipcc and hipconfig script for better readability

### ISSUE THREAD

**Issue by yan-ming** [GPUOpen-ProfessionalCompute-Tools/HIP#25]
Hi,

In `hipcc` and `hipconfig` script, I see a lot of `unless defined` idioms used for setting default values of flags, such as the following:

```
	$HSA_PATH=$ENV{'HSA_PATH'};
	$HSA_PATH="/opt/rocm/hsa" unless defined $HSA_PATH;
```

This can be replaced by Perl's logic-defined-or operator `//`, which literally means setting the default value for Perl people.

```
	$HSA_PATH = $ENV{'HSA_PATH'} // "/opt/rocm/hsa";
```

Reference:

http://perldoc.perl.org/perlop.html#Logical-Defined-Or
http://perlmaven.com/how-to-set-default-values-in-perl

**Comment by mangupta** [comment]
`hipcc` and `hipconfig` on the [developer-preview branch](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/tree/developer-preview) now use Logical-Defined-Or.
