### ISSUE TITLE
Forcing HIP runtime initialization before starting time counter

### ISSUE THREAD

**Issue by rjfnobre** [GPUOpen-ProfessionalCompute-Tools/HIP#26]
When using CUDA, and measuring time for the execution of a kernel, I'm used to call 'cudaFree(0)' before starting to count time.
The call of 'cudaFree(0)' forces the CUDA runtime to initialize before starting the time counter.  

E.g.:

// So that the CUDA runtime is initialized before starting measuring time
cudaFree(0);

struct timespec t_start, t_stop;
clock_gettime( CLOCK_MONOTONIC, &t_start);
deviceReduceKernel <<<numBlocks_red, threadsPerBlock_red>>> (distmat_d, sum_perblock_d, totalNumElementsDistmat);
clock_gettime( CLOCK_MONOTONIC, &t_stop);

How could I achuive the same (force runtime intialization) when using HIP?

Using 'hipFree(0)' instead of 'cudaFree(0)' does not result in the same behavior, as the elapsed time as reported by the timer remais the same as when not calling 'hipFree(0)'.

**Comment by adityaatluri** [comment]
My guess would HCC puts `ihipInit()` function call at the start of `main()`. @bensander , @mangupta can you comment on this?

**Comment by rjfnobre** [comment]
Were can I get confirmation for thi?

**Comment by bensander** [comment]
This was a bug and was fixed in hip 0.90 : calling hipFree(0) initializes the runtime and returns hipSuccess.
