### ISSUE TITLE
Missing hipLaunchParm after hipify

### ISSUE THREAD

**Issue by LWisteria** [GPUOpen-ProfessionalCompute-Tools/HIP#27]
When I convert below code from CUDA to HIP by hipify (hipconvertinplace.sh)

```
# kernel.cu
__global__
void kernel(double z[], const double x[], const double y[])
{
    const auto i = (blockIdx.x * blockDim.x + threadIdx.x);

    z[i] = x[i] + y[i];
}
```

and compile them, I got an error.

```
kernel.cu:8:27: error: hc_grid_launch function must have grid_launch_parm type as first parameter, 'double *' type is not compatible
void kernel(double z[], const double x[], const double y[])
                          ^
kernel.cu:19:34: error: no matching function for call to 'kernel'
        hipLaunchKernel(HIP_KERNEL_NAME(kernel), dim3(block), dim3(thread), 0, 0, z, x, y);
                                        ^~~~~~
/opt/rocm/include/hip/hcc_detail/hip_runtime.h:529:30: note: expanded from macro 'HIP_KERNEL_NAME'
#define HIP_KERNEL_NAME(...) __VA_ARGS__
                             ^
/opt/rocm/include/hip/hcc_detail/hip_runtime.h:552:3: note: expanded from macro 'hipLaunchKernel'
  _kernelName (lp, ##__VA_ARGS__);\
  ^
kernel.cu:8:13: note: candidate function not viable: requires 3 arguments, but 4 were provided
void kernel(double z[], const double x[], const double y[])
```

"hipLaunchParm" seems missing so I can solve this error by manually adding "hipLaunchParm lp" at kernel's first argument.

Is it hard to automatically add "hipLaunchParm lp" by hipify converter?

**Comment by mangupta** [comment]
The hipify tool is a perl script and converts code using find and replace. So adding the hipLaunchParm as the kernel's first argument is a manual step as noted in this [blog post](http://gpuopen.com/hip-to-be-squared-an-introductory-hip-tutorial/).

However, there is a newer experimental tool based on clang that is available in the repo under the clang-hipify folder. Refer to clang-hipify [README.md](http://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/clang-hipify/README.md) for instructions on building and using this tool.

**Comment by LWisteria** [comment]
@mangupta 
Thank you.

clang-hipify works fine but it cannot convert *.c and *.cpp which uses CUDA Runtime API (e.g. cudaMalloc or cudaMemcpy).
So we need
* clang-hipify for *.cu
* (original) hipify for other files using CUDA Runtime API

Is it right?

**Comment by mangupta** [comment]
clang-hipify should be able to consume *.c, *.cpp, *.cu, or any other extensions that you might be using. However it does expect a .cu extension in the output filename. Can you try again by specifying -o <outputfileName> instead of using the -inplace option?

**Comment by LWisteria** [comment]
@mangupta 

"-inplace" option works and "-o" too.

```
# NG
$ /opt/rocm/hip/bin/hipify-clang main.cpp
Input .cu file was not specified.

# OK
$ /opt/rocm/hip/bin/hipify-clang main.cpp -o main.hip.cpp

# OK
$ /opt/rocm/hip/bin/hipify-clang main.cpp -inplace
```

In my understanding, hipify-clang always needs output file name. so
* "/opt/rocm/hip/bin/hipify-clang [A] -o [B]" works instead of "hipify [A] > [B]"
* "/opt/rocm/hip/bin/hipify-clang [A] -inplace" works instead of "hipify [A] -inplace"
* "/opt/rocm/hip/bin/hipify-clang [A]" doesn't works.

**Comment by emankov** [comment]
Current version of clang-hipify works fine with any file extension if -- delimeter is specified at the end of command line after all clang-hipify options. Clang options (if needed, for instance -I) should be specified after -- delimeter.

**Comment by emankov** [comment]
1. Output filename (-o) is optional. 
2. To feed clang-hipify files with any extension or without extension at all, please specify "-x cuda" option after "--" delimeter.
3. Directories are not supported.
