### ISSUE TITLE
Finding good flags for the 'hipcc' compiler

### ISSUE THREAD

**Issue by rjfnobre** [GPUOpen-ProfessionalCompute-Tools/HIP#28]
What parameters should I pass to 'hipcc' so that it will most likely result in the fastest possible device code being generated?

For instance, with 'nvcc' (NVIDIA's compiler) I use '--use-fast-math' wich sets '--prec-div=false' and '--prec-sqrt=false', so that the resulting compiled device code is faster as the cost of precision.

Does the 'hipcc' '-ffast-math' accomplish the same thing?

**Comment by adityaatluri** [comment]
We added support for it

https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/developer-preview/include/hip/hcc_detail/hip_runtime.h#L519

Instead of --use-fast-math, you can try -DHIP_FAST_MATH. Using CUDA fast math flag for compilation will be added soon.
