### ISSUE TITLE
__HIPCC__ not defined in HIP

### ISSUE THREAD

**Issue by ekondis** [GPUOpen-ProfessionalCompute-Tools/HIP#29]
The `__HIPCC__` predefined macro seems not to be defined during compilation. Here is a test case with the following source:

```
#include <stdio.h>

int main(int argc, char* argv[]) {
#ifdef __HIPCC__
	printf("__HIPCC__ is defined\n");
#endif
#ifdef __CUDACC__
	printf("__CUDACC__ is defined\n");
#endif
#ifdef __HCC__
	printf("__HCC__ is defined\n");
#endif
	return 0;
}
```

After compiling with hipcc (/`opt/rocm/bin/hipcc -o test-macro -O2 -I/opt/rocm/hip/include test-macro.cpp`) and running, it returns just the following output:

`__HCC__ is defined`

**Comment by pfultz2** [comment]
The compiler makes two passes over the source code, once for the cpu target and another for the gpu target, and the discards the source code that is not meant for the target. I believe the `__HIPCC__` macro is only define during the gpu pass, so it would not show up on your test.

**Comment by mangupta** [comment]
@ekondis The `__HIPCC__` macro is defined by hip_runtime headers and not by hipcc. Modifying the above code to include "hip_runtime.h" fixes the issue.

**Comment by ekondis** [comment]
Including "hip_runtime.h" fixes the issue.
