### ISSUE TITLE
HIP with NVIDIA

### ISSUE THREAD

**Issue by rjfnobre** [GPUOpen-ProfessionalCompute-Tools/HIP#30]
When compiling on a machine with an AMD card I do the following and it works:
gcc -c main.c misc.c -DTYPE=float
hipcc -O2 Kernel.hip.cpp main.o misc.o -DTYPE=float -o kernel_hip_float

But when compiling a machine with an NVIDIA card (and with theCUDA toolkit installed) I get lots of 'warning: null character(s) ignored' and 'error: unrecognized token' errors (reported for the 'main.o' object file) when executing the second command.

What is the correct way of compiling and linking multiple files, where only a single file includes the HIP runtime library (in this example 'Kernel.hip.cpp')?

**Comment by mangupta** [comment]
Splitting the second step into a separate compilation and linking step should fix the problem i.e. do something like:
```shell
hipcc -O2 -c Kernel.hip.cpp -DTYPE=float -o Kernel.hip.o
hipcc Kernel.hip.o main.o misc.o -o kernel_hip_float
```
The problem is due to the way nvcc tries to detect if the file needs to be compiled using CUDA mode or pass-through CPP mode.
