### ISSUE TITLE
Java bindings

### ISSUE THREAD

**Issue by almson** [GPUOpen-ProfessionalCompute-Tools/HIP#32]
Hi, I am cross-posting this request in the JCUDA repo as well. (https://github.com/jcuda/jcuda/issues/5)

JCUDA is a set of Java bindings for the CUDA API (both Driver API and the parts of Runtime API) and associated libraries (cuBLAS, cuDNN, etc.). It's simple, straight-forward, and works very well with no performance impact.

I'd love to jump into HIP by converting my existing JCUDA code. Is there any chance you could collaborate with the JCUDA project or create an analogous library?

**Comment by adityaatluri** [comment]
Hi,
I am willing to lend you some help where needed. @bensander any comments?

**Comment by almson** [comment]
@adityaatluri I'm slowly chugging along with this, but I hit a roadblock. The method to launch kernels is fubar.

You're probably aware of this, but I'll restate the problem. CUDA has two ways of launching kernels. The first, called the "Runtime API," uses magic. The other, called "Driver API," uses plain C. Interop libraries like JCuda use the plain C method, for obvious reasons. Since Runtime API and Driver API calls can be mixed and matched at will, using the Driver API for this purpose is pretty easy. The user calls `cuModuleLoad` to load a ptx, cubin, or fatbin (that may have been pre-compiled and bundled in the JAR), gets a function pointer with `cuModuleGetFunction`, creates an array to hold kernel parameters, and calls `cuLaunchKernel`. Take a look at this JCuda sample titled [JCudaVectorAdd](http://jcuda.org/samples/samples.html). (The sample is purely Driver API, but like I mentioned operations like memory copies can be done with the Runtime API.)

HIP needs to expose this alternative way to launch kernels, and include it in `hip_runtime_api.h`, or else interop with Java (or any other language) cannot happen in a sane way.

**Comment by almson** [comment]
It's also annoying that the header changes depending on whether it targets HCC or CUDA. This means there would essentially be two sets of bindings and I would need to write the code that makes switching between HCC and CUDA more transparent. I was hoping to rely more on HIP for this.

**Comment by adityaatluri** [comment]
Hi,
First of, we have CUDA Driver API in our mind. HIP should be able to take care of CUDA path and HCC path. It should be easy for you to develop on HIP and map to different path as you want. If you want a standalone one, you can specify HIP which path it should take using HIP_PLATFORM env variable.
And, thank you for the example. 
Let us know if you need anything.

**Comment by jcuda** [comment]
I'll try to rephrase the questions, hoping that I understood them correctly:

1. The header issue: The current way of switching between the NVCC and the HCC path is to either define `__HIP_PLATFORM_HCC__` or `__HIP_PLATFORM_NVCC__`  at compile time in the application that uses HIP. There does not seem to be a way to create a HIP application that is implemented against some HIP interface" and *dynamically* links against some "HIP library". Parts of this could probably be solved by pulling out the HIP runtime API parts into a common HIP runtime header, as described in https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/include/nvcc_detail/hip_runtime_api.h#L31 , making sure that this interface does not depend on any particular (NVCC or HCC) backend. Right now, there are *two* distinct "`detail`" runtime API headers, which makes it impossible to create a real interface library. 

2. The module loading issue: Currently, the kernel is always compiled into the application. There seems to be no way to *only* compile a kernel into any form of "binary", and load this binary programmatically. I'm not sure how this could be solved in general (I'm not yet familiar enough with the backends, particularly with the HCC backend). Maybe it's possible to compile only the kernel into some .DLL (or... `.SO`... but that's another point), and let the application load this dynamically at runtime (maybe with some `dlopen`/`dlsym` magic). But a built-in solution for "binary (loadable) representations of kernels" would probably be preferable.

**Comment by almson** [comment]
Searching `HIP_PLATFORM` led me to this page: [Platform-Aware Coding Inside HIP](http://gpuopen.com/platform-aware-coding-inside-hip/), where it's merely a variable inside a Makefile.

@adityaatluri Could you give a little background on who you are? Do you work for AMD? What do you work on beside HIP?

**Comment by adityaatluri** [comment]
Hi @almson ,
Sorry about that. I meant `__HIP_PLATFORM_HCC__`. I work at AMD on bringing up the HIP API.

**Comment by almson** [comment]
@adityaatluri Isn't that a compile-time define? You made it sound like it's a runtime variable. From my understanding, an application can be compiled to either target HCC or to target CUDA. Not both. It can't switch at runtime.

**Comment by bensander** [comment]
Hi @almson - HIP provides both a compile-time way to detect the platform (__HIP_PLATFORM_HCC__, __HIP_PLATFORM_NVCC__) and a binary tool that detects the current platform (that's hipconfig, which in in the examples is used inside the Makefile).  Both are useful - the first lets you conditionally compile platform-specific code.  The second lets you perform platform-specific make steps like including different libraries or passing different options to the compiler.

**Comment by almson** [comment]
@bensander Alright, but it's still all compile-time. In Java-interop-land, we don't compile native code on users' machines. We ship pre-compiled binaries in jar files. Usually, these binaries are thin wrappers that load dynamic libraries from the system (the wrappers expose native functions with specific interfaces, following the JNI spec, that Java can link to and call directly). That is how the JCuda library works. I was hoping that HIP would be a single dynamic library. As I see it, it would still be possible to compile two wrappers, with the actual switching logic implemented in Java. A bit inconvenient, but doable.

Do you have a time estimate when you'll expose the loading of pre-built hsaco binaries as detailed here: http://gpuopen.com/rocm-with-harmony-combining-opencl-hcc-hsa-in-a-single-program/ ?

**Comment by adityaatluri** [comment]
Hi @almson ,
For Driver API, we have it in our discussions. If we support it, it'll be similar to how CUDA does it.

**Comment by almson** [comment]
May I ask why you chose to write your own C++ parser instead of using one of many third-party ones? The Eclipse parser opens `hc.hpp` without problems (try it: https://github.com/almson/eclipse-cdt-standalone-astparser). There's other options too: https://stackoverflow.com/questions/12865587/parsing-c-source-code-in-java-environment

**Comment by almson** [comment]
I apologize for the last comment, that was meant for another thread. (I'm trying to get JavaCPP to parse hc.hpp header.)

**Comment by almson** [comment]
@bensander Also, please write a decent implementation of SGEMM. I don't just mean expose cuBLAS. I mean write something in assembly that beats its performance.

**Comment by bensander** [comment]
Yes, it’s coming.  Assembler is one piece of the puzzle.

**Comment by adityaatluri** [comment]
As the conversation is inactive, closing the issue.

**Comment by jcuda** [comment]
As a (last?) ping: @almson Any plans to fill https://github.com/almson/jhip ? (Although there was no more discussion in the [forum thread](https://forum.byte-welt.net/byte-welt-projekte-projects/jcuda/20996-hip-amds-cuda-clone-support-2.html#post139424) either...)

**Comment by almson** [comment]
@jcuda Some teething problems with ROCm (lack of ZFS modules in their kernel) have prevented me from working on it lately. I've been waiting for ROCm to mature (and move to kernel modules). On the bright side, it's my impression that HIP now exposes the bits of the driver API that allows loading binary kernels. So... I'll get to it eventually.

**Comment by bensander** [comment]
Yes, HIP does support some of the key components of the driver API, notably the ability to explicitly load and launch code modules.  See 👍 https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/docs/markdown/hip_porting_driver_api.md
