### ISSUE TITLE
hipify tensorflow?

### ISSUE THREAD

**Issue by allthetime** [GPUOpen-ProfessionalCompute-Tools/HIP#37]
Hi. 

I'm curious if anyone has tried doing this, or is working on doing so...

If not, how, generally, could I accomplish this?

**Comment by bensander** [comment]
Hi – TensorFlow is based on an open-source runtime called StreamExecutor.  StreamExecutor uses the CUDA Driver API, which was not supported by HIP – until yesterday that is!    The new developer-preview branch contains new APIs to load code Modules and manipulate Contexts.  It also adds a cross-platform device compiler to hipcc, so you can convert HIP kernels into .PTX on Nvidia side or “hsaco” code objects on the AMD side.    We have a team looking at StreamExecutor and TensorFlow support on the HIP infrastructure.

The HIP developer preview branch requires new features from HCC and should be used with the “develop” branch of HCC.  Here are some more relevant links to the branch and documentation:
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/tree/developer-preview
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/developer-preview/docs/markdown/hip_porting_driver_api.md

-ben

**Comment by allthetime** [comment]
@bensander yesterday!? great news. Thanks for taking the time to answer.
