### ISSUE TITLE
functions that differ only in their return type cannot be overloaded * 5

### ISSUE THREAD

**Issue by Dekken** [GPUOpen-ProfessionalCompute-Tools/HIP#38]
Hi,

I'm running [Crunchbang++](https://crunchbangplusplus.org/) (debian jessie kernel [4.7pf](https://github.com/pfactum/pf-kernel/releases/tag/v4.7-pf2))

I'm trying out hcc built from this script (build_hcc_and_hip.sh - can't remember where I found it now)
It's probable I'm doing something wrong or have forgot to do something, but with hcc/hip/llvm trying to build a simple "hipified" (slightly modified) [cuda example](http://computer-graphics.se/multicore/pdf/hello-world.cu), you can see [here](http://pastebin.com/zGJ6LGji)

I get the following [error](http://pastebin.com/U29kTbcd)

**Comment by Dekken** [comment]
Will try with the ROCM 4.4 kernel and post again.

**Comment by adityaatluri** [comment]
Fixed with developer_preview branch. Can you check it?
