### ISSUE TITLE
Missing API hipEventDisableTiming for nvcc path

### ISSUE THREAD

**Issue by yan-ming** [GPUOpen-ProfessionalCompute-Tools/HIP#40]
`hipEventDesableTiming` is detined in `hcc_detail/hip_runtime_api.h` but not in `nvcc_detail/hip_runtime_api.h`. Need a substitution from `hipEventDisableTiming` to `cudaEventDisableTiming`

**Comment by sunway513** [comment]
Hi Yan-Ming,
Can you try the attached patch? 
It is for HIP [preview_0.92.16375 ](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/releases/tag/preview_0.92.16375) release.

[hipeventNV.zip](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/files/499906/hipeventNV.zip)
