### ISSUE TITLE
missing hipArray APIs in nvcc path

### ISSUE THREAD

**Issue by yan-ming** [GPUOpen-ProfessionalCompute-Tools/HIP#42]
hipArray APIs, such as `hipArray`, `hipMallocArray`, ... etc are missing in nvcc path. Need to map them in `include/nvcc_details/hip_runtime_api.h`.

**Comment by yan-ming** [comment]
`hipMemcpy2D` is also missing. Also, hipArray test seems to be disabled currently?

**Comment by adityaatluri** [comment]
Hi @yan-ming ,
Thank you for pointing out the issues. I am working on refactoring hipArray for nvcc and hcc path.

**Comment by adityaatluri** [comment]
Fixed with developer_preview branch. Can you check it?
