### ISSUE TITLE
hipStreamAddCallback compile error

### ISSUE THREAD

**Issue by dinosaur8312** [GPUOpen-ProfessionalCompute-Tools/HIP#46]
Hi,
 
I got the following error when trying to compile the sample square code:

/opt/rocm/hip/bin/hipcc square.hipref.cpp -o square.hip.out
/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(588): error: type name is not allowed

/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(588): error: expected a ")"

/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(588): error: too few arguments in function call

/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(589): error: type name is not allowed

/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(589): error: expected a ")"

/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(589): error: too many arguments in function call

/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(589): error: expected a ";"

7 errors detected in the compilation of "/tmp/tmpxft_0000396e_00000000-9_square.hipref.cpp1.ii".
Died at /opt/rocm/hip/bin/hipcc line 365.
make: *** [square.hip.out] Error 2

The line 588 and 589 of hip_runtime_api.h is:

inline static hipError_t hipStreamAddCallback(hipStream_t stream, hipStreamCallback_t callback, void *userData, unsigned int flags)
{
    return **hipCUDAErrorTohipError(cudaStreamAddCallback(cudaStream_t stream,
        cudaStreamCallback_t callback, void *userData, unsigned int flags));**
}

Shouldn't brackets to be add to each type name here?

Thanks,

**Comment by sunway513** [comment]
Hi, could you try to use a newer HIP release? Such as the following one:
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/releases/tag/release_1.0.16435
I just tried the square sample, it works fine on my config on NVidia machine.
If you still have a problem after a newer HIP, please provide your hipconfig information here.

**Comment by dinosaur8312** [comment]
Hi, 

I have upgraded the version, but still got the same error.

I don't think including the typename when calling a function as in the /opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h is the right way.

inline static hipError_t hipStreamAddCallback(hipStream_t stream, hipStreamCallback_t callback, void *userData, unsigned int flags)
{
    return hipCUDAErrorTohipError(cudaStreamAddCallback(cudaStream_t stream,
        cudaStreamCallback_t callback, void *userData, unsigned int flags));
}

I posted the hip version info and hipconfig info here:

opt/rocm/hip/bin/hipcc --version
HIP version: 1.0.16453
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

/opt/rocm/hip/bin/hipconfig --full
HIP version  : 1.0.16453

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/include -I/cgv/Compilers/nvidia/CUDA-7.5.18/include

== nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Wed_Jul_17_18:36:13_PDT_2013
Cuda compilation tools, release 5.5, V5.5.0

=== Environment Variables
PATH=/usr/local/cuda/bin:.:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/etc:/usr/bin/X11:/cgv/Compilers/intel/compiler-14.0.1/bin:/tad/local/lam-7.1.4/bin
LD_LIBRARY_PATH=/cgv/Compilers/nvidia/CUDA/lib64:/cgv/Compilers/nvidia/CUDA-3.2/lib64:/cgv/Compilers/nvidia/CUDA-5.0.35_db6/lib64:/cgv/Compilers/nvidia/CUDA-5.5.22_db6/lib64:/cgv/Compilers/mpi/openmpi/lib64:/cgv/Compilers/intel/compiler-14.0.1/composer_xe_2013_sp1.1.106/compiler/lib/intel64:/cgv/Compilers/intel/compiler-14.0.1/composer_xe_2013_sp1.1.106/mpirt/lib/intel64:/cgv/Compilers/intel/compiler-14.0.1/composer_xe_2013_sp1.1.106/ipp/../compiler/lib/intel64:/cgv/Compilers/intel/compiler-14.0.1/composer_xe_2013_sp1.1.106/ipp/lib/intel64:/cgv/Compilers/intel/compiler-14.0.1/composer_xe_2013_sp1.1.106/mkl/lib/intel64:/cgv/Compilers/intel/compiler-14.0.1/composer_xe_2013_sp1.1.106/tbb/lib/intel64/gcc4.4:/TANGO/3/rel/lib:/vega/1/rel/Oracle/lib:
CUDA_CACHE_DISABLE=1
CUDA=/cgv/Compilers/nvidia/CUDA-7.5.18
CUDA_PATH=/cgv/Compilers/nvidia/CUDA-7.5.18

== Linux Kernel
Hostname     : hougpu002
Linux hougpu002 3.14.19-grml64w-01 #1 SMP Fri Sep 19 15:34:40 CDT 2014 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy

**Comment by sunway513** [comment]
Hi,
Thank you for the additional information and pointing out this issue.
Did you modify the square sample? If so, could you share it here?
There are errors in this API translation, please let me know if the attached patch could solve it for you.
[callback.patch.zip](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/files/581437/callback.patch.zip)

**Comment by dinosaur8312** [comment]
Hi, 

The issue is gone if I manually modify the header file by add brackets to each argument as follow:

inline static hipError_t hipStreamAddCallback(hipStream_t stream, hipStreamCallback_t callback, void *userData, unsigned int flags)
{
return hipCUDAErrorTohipError(cudaStreamAddCallback((cudaStream_t) stream,
(cudaStreamCallback_t) callback, (void *)userData, (unsigned int) flags));
}

I haven't try the patch yet. But I think it should work if it give similar fix.

Thank you!
