### ISSUE TITLE
Kernel with no parameters

### ISSUE THREAD

**Issue by ArchaeaSoftware** [GPUOpen-ProfessionalCompute-Tools/HIP#48]
A kernel with no parameters (from cudahandbook/concurrency/nullKernelSync.cu, for example) generates the appended compile error.

Adding a dummy int parameter fixes the problem.

/opt/rocm/hip/bin/hipcc -stdlib=libc++ -Wnull-character -I ../chLib -D NO_CUDA nullKernelSync.cpp -o nullKernelSync
nullKernelSync.cpp:67:9: error: expected expression
        hipLaunchKernel(HIP_KERNEL_NAME(NullKernel), dim3(1), dim3(1), 0, 0, );
        ^
/opt/rocm/hip/include/hip/hcc_detail/hip_runtime.h:541:33: note: expanded from
      macro 'hipLaunchKernel'
  _kernelName (lp, ##__VA_ARGS__);\
                                ^
1 error generated.
Died at /opt/rocm/hip/bin/hipcc line 269.

**Comment by adityaatluri** [comment]
Hi @ArchaeaSoftware ,
Did you use hipify? Here is a sample null kernel code.
```
#include<hip/hip_runtime.h>
#include<hip/hip_runtime_api.h>

__global__ void Kernel(hipLaunchParm lp) {}

int main(){
hipLaunchKernel(Kernel, dim3(1,1,1), dim3(1,1,1),0,0);
}
```

**Comment by sunway513** [comment]
Hi, the parameter of hipLaunchParm is currently required for any HIP kernels.
It's related to how we process and launch kernels through our compiler stack with HCC.
As Aditya pointed out, "__global__ void Kernel(hipLaunchParm lp) {}" is equavelunt to NULL kernel for HIP. 
On NVCC path, the kernel parameter lp will be ignored; thus, the above kernel perfectly equal to NULL kernel defined in CUDA.
