### ISSUE TITLE
Add performance comparison with OpenCL

### ISSUE THREAD

**Issue by RasmusWL** [GPUOpen-ProfessionalCompute-Tools/HIP#50]
I've been looking for a performance comparison of using using HCC (through HIP) vs OpenCL. But I haven't been able to find any :worried:

I see there is an issue for porting the [PARBOIL benchmark suite](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/issues/3), but that is not completed yet. 

The Rodinia benchmark suite seems to be ported (as mentioned in the README), but I can't find any performance graphs. The same goes for `mixbench` and `GPU-Stream` mentioned in the [HIP-Examples](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP-Examples) repo.

It would be great to have performance graphs readily available. It could also be fun to have a server run such benchmarks every week or so, as rust does: http://perf.rust-lang.org/

keep up the good work :+1:

**Comment by adityaatluri** [comment]
Hi,
You can find hip branch on [SHOC](https://github.com/vetter/shoc/tree/hip) to benchmark against OpenCL

**Comment by RasmusWL** [comment]
Hi, and thanks for responding :)

What I'm looking for is not more benchmarks, but the results of such benchmarks to comparing the performance between HCC and OpenCL on AMD GPUs, without having to run the benchmarks myself.

My point is that it would be a valuable asset to add such readily available performance measurements and graphs to the README of this github repo. I'm not saying it is not possible to run these benchmarks yourself if you have the hardware, I'm just saying it would be nice to get an idea of what to expect up front, and hopefully also to pique the interest of users stopping by to see what this hip thing is.

As an example of what I am looking for, I could point to [Zstandard](https://github.com/facebook/zstd).

**Comment by adityaatluri** [comment]
Gotcha! Well, the TFLOPs we show in marketing slides are the ones to start. Let me see what I can do for the charts.

**Comment by sunway513** [comment]
Hi, if you are looking at quick results comparision between OpenCL and HIP on the same AMD device, there are two public bencharks has such logs available:
https://github.com/ekondis/mixbench/tree/master/results
https://github.com/UoB-HPC/GPU-STREAM/tree/master/results

I would say these information are interesting and important, but not quite aligned with the goal of HIP repository. 
Please let us know if there's anythig further we can help.
