### ISSUE TITLE
function "hipDeviceGetPCIBusId" has already been defined

### ISSUE THREAD

**Issue by thearchitect** [GPUOpen-ProfessionalCompute-Tools/HIP#59]
Error building HIP/samples/2_Cookbook/0_MatrixTranspose:
`# make`
results in
`/opt/rocm/hip/include/hip/nvcc_detail/hip_runtime_api.h(778): error: function "hipDeviceGetPCIBusId" has already been defined`

Dockerfile for developer image:
```Dockerfile
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04

RUN \
	apt-get update && \
	apt-get install -y wget

RUN \
	wget -qO - http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
	sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list' && \
	apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y hip_nvcc
ENV PATH /opt/rocm/bin/:$PATH


```

**Comment by thearchitect** [comment]
Same error when building other samples

**Comment by gargrahul** [comment]
Can you try by commenting following in
*HIP_ROOT/include/hip/nvcc_details/hip_runtime_api.h*

inline static hipError_t hipDeviceGetPCIBusId(char* pciBusId,int len,int
device)
{
    return
hipCUDAErrorTohipError(cudaDeviceGetPCIBusId(pciBusId,len,device));
}

**Comment by thearchitect** [comment]
Hi gargrahul!

Sure, I'll do it right now.

BTW I've found this code in intermediate file `MatrixTranspose.cpp1.ii` on lines `54195-54203`:
```c++
inline static hipError_t hipDeviceGetPCIBusId(char* pciBusId,int len,int device)
{
    return hipCUDAErrorTohipError(cudaDeviceGetPCIBusId(pciBusId,len,device));
}

inline static hipError_t hipDeviceGetPCIBusId(char* pciBusId,int len,hipDevice_t device)
{
    return hipCUResultTohipError(cuDeviceGetPCIBusId(pciBusId,len,device));
}
```

**Comment by thearchitect** [comment]
Removed these lines. Now it's working.
Thank you!

**Comment by thearchitect** [comment]
gargrahul, could you please explain what was wrong?

**Comment by gargrahul** [comment]
On HIP/NVCC path hipDeviceGetPCIBusId(char* pciBusId,int len,int device)
was already implemented as hipDeviceGetPCIBusId(char* pciBusId,int
len,hipDevice_t device) since hipDevice_t is type defined to CUDevice
(which is type defined to int in CUDA)

**Comment by thearchitect** [comment]
Thanks again, gargrahul!
Should I close this issue?

**Comment by antoinewdg** [comment]
I'm getting the same error after building from source (commit f052f43b3b3d48ac79f2111c7da74c24f1ad29b2). The fix works for me, but editing source doesn't feel like a solution...

**Comment by mangupta** [comment]
This was fixed in the developer-preview branch on Dec 20th (commit [4704547](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/commit/4704547bab722ecb99a72e5bda631065b300a848)). All development and bug fixes happen in the developer-preview branch before being merged into the master branch. Refer to the HIP [README.md](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP#repository-branches) for details.

**Comment by antoinewdg** [comment]
Thanks for the info !
