### ISSUE TITLE
Support VISIBLE_DEVICES environment var

### ISSUE THREAD

**Issue by bensander** [GPUOpen-ProfessionalCompute-Tools/HIP#6]
use an environment variable to control which devices are made visible to the application.  
 - support comma-separated list of device IDs.
 - order of device ids in the env var control order in the application, ie 2,1,0 will cause HW device 2 to be listed at device0 in the app.

Implementation:
  - modify src/hip_hcc.cpp ihipInit to use env variable to control which of the detected devices get added to the "g_devices" list, and also control the order they get added in.

**Comment by bensander** [comment]
will be in next release

**Comment by adityaatluri** [comment]
@sunway513 Can I close it?

**Comment by sunway513** [comment]
Sure, I think this has been fullfilled.
Thanks!

On Tue, Mar 8, 2016 at 10:32 AM, Aditya Atluri <notifications@github.com>
wrote:

> @sunway513 <https://github.com/sunway513> Can I close it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/issues/6#issuecomment-193851497>
> .
>



-- 
Best Regards,
Peng

**Comment by adityaatluri** [comment]
Closing. Finished by @sunway513
