### ISSUE TITLE
cuda math intrinsic functions support

### ISSUE THREAD

**Issue by 3upperm2n** [GPUOpen-ProfessionalCompute-Tools/HIP#61]
Hello,

I found that the math intrinsics on cuda, such as __float2int_rn, are not supported by hipcc. Can you confirm this? If not, how to make it work?

Best,
Leiming

p.s. Here is a snippet of the error message I got by running the following command with rocm.
```
$ /opt/rocm/hip/bin/hipcc  -I/opt/rocm/hip/include  -std=c++11 -fopenmp -DUSE_ATOMIC  -DSAVE_DETECTORS -DUSE_CACHEBOX  -DMCX_TARGET_NAME='"Fermi MCX"' -o mcx_core.o  mcx_core.cu
mcx_core.cu:182:30: error: use of undeclared identifier '__float2int_rn'
      xi[0] = mcx_nextafterf(__float2int_rn(htime[0]), (v->x > 0.f)-(v->x < 0.f));
```

**Comment by adityaatluri** [comment]
We are working on it.

**Comment by adityaatluri** [comment]
Fixed with developer_preview branch. Can you check it?
