### ISSUE TITLE
no matching function for call to 'hipHostGetDevicePointer'

### ISSUE THREAD

**Issue by 3upperm2n** [GPUOpen-ProfessionalCompute-Tools/HIP#63]
Hello,

Is hipHostGetDevicePointer supported in hipcc?

Here is my experiment.
The progress is allocated on the host using pinned memory.
```cpp
CUDA_ASSERT(hipHostMalloc((void **)&progress, sizeof(int), hipHostMallocMapped))
```

However, when I try to get the device pointer, the following error shows.
```bash
mcx_core.cu:1301:18: error: no matching function for call to 'hipHostGetDevicePointer'
     CUDA_ASSERT(hipHostGetDevicePointer((int **)&gprogress, (int *)progress, 0));
```

**Comment by gargrahul** [comment]
Can you try hipHostMalloc
<https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/developer-preview/tests/src/hipHostMalloc.cpp>test
sample ?

**Comment by 3upperm2n** [comment]
After changing int to void in the hipHostGetDevicePointer(), the error disappears.
Thanks!  @gargrahul
