### ISSUE TITLE
build error of fp16 in developer-preview branch

### ISSUE THREAD

**Issue by tingxingdong** [GPUOpen-ProfessionalCompute-Tools/HIP#67]
I am building the "developer-preview branch" of HIP. My hcc compiler is  "HCC clang version 3.5.0  (based on HCC 0.10.16501-81f0a2f-02246a0 LLVM 3.5.0svn)" based on rocm-1.4.

I see the compiler error:
 "/home/tim/HIP/src/hip_fp16.cpp:37:12: error: invalid operands to binary expression ('__half' and '__half')"
  return a + b;
         ~ ^ ~

**Comment by sunway513** [comment]
Hi Tingxing, when you build HIP it's highly recommended to build with an updated version of HCC as well. Please consider using the this [script](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/releases/download/preview_1.0.17066/build_hcc_and_hip.sh) to build the latest DP release of HIP and HCC.
