### ISSUE TITLE
hipblas.h not found

### ISSUE THREAD

**Issue by psteinb** [GPUOpen-ProfessionalCompute-Tools/HIP#68]
Hi, I just wanted to play around with the hip samples that come with rocm 1.4. I went into `samples/7_Advanced/hipblas_saxpy` and called `make` and received this:

```
saxpy.hipblasref.cpp:9:10: fatal error: 'hipblas.h' file not found
#include <hipblas.h>
         ^
1 error generated.
Died at /opt/rocm/hip/bin/hipcc line 378.
```

related to this, I was wondering how to use hipBlas, hipFFT, hipRNG?

**Comment by psteinb** [comment]
I should add that I cloned this repo and tries the same from this [folder](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/tree/master/samples/7_Advanced/hipblas_saxpy) with the same result

**Comment by sunway513** [comment]
Hi, could you install hipblas with the following commands?
_cd ~ && git clone -b master https://bitbucket.org/multicoreware/hcblas.git && cd hcblas && ./build.sh && sudo dpkg -i build/*.deb
cd /opt/rocm/hcblas/lib && sudo ln -s libhipblas_hcc.so libhipblas.so_
hipblas will be installed to /opt/rocm/hcblas by default.

**Comment by psteinb** [comment]
Thanks for your answer.

I see the `hip`Libs are inside the `hc`Libs. It would be nice if that 
would be documented somewhere. I wasn't aware of that.

hcBlas is not contained in the rocm repo as a package AFAIK.

**Comment by sunway513** [comment]
Yes, hipblas is a wrapper of cublas and hcblas. It translates hipblas APIs to either cublas or hcblas routines based on the underlying platform; and since that is through header files, there's no performance loss. 
Thanks for your suggestions, we'll add more instructions on those hip* libraries.

**Comment by psteinb** [comment]
great to hear that.

**Comment by bensander** [comment]
Peter I suspect you are using the master branch of HIP, which is the default.   At this point developer-preview is more up-to-date and likely a better choice.  In fact I believe we removed this sample from developer preview at some point since the hipblas implementation moved elsewhere.
