### ISSUE TITLE
hipify inplace appears misimplemented

### ISSUE THREAD

**Issue by hgaspar** [GPUOpen-ProfessionalCompute-Tools/HIP#7]
Didn't work for me.  I called it as follows:
First, cd to directory that contains cuda files. Then
 ../../../GPUOpen-ProfessionalCompute-Tools/HIP/bin/hipify "inplace" ./*.cu

OR

 ../../../GPUOpen-ProfessionalCompute-Tools/HIP/bin/hipify inplace ./*.cu

produce error:

error: could not open inplace at ../../../GPUOpen-ProfessionalCompute-Tools/HIP/bin/hipify line 189.

**Comment by bensander** [comment]
Correct syntax is "hipify -inplace" (with dash on the option).
Also you may find the [convertinplace.sh](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/bin/hipconvertinplace.sh) script interesting - this finds all code files in a directory and converts them all in-place.
