### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by BeamOfLight** [GPUOpen-ProfessionalCompute-Tools/HIP#74]
Hello! I try to compile caffe 1.0.0-rc3 with HIP. There are some errors like:

/home/beamoflight/caffe/caffe/src/caffe/util/im2col.cu(57): error: no instance of function template "caffe::im2col_gpu_kernel" matches the argument list
            argument types are: (int, int, const float *, const int, const int, const int, const int, const int, const int, const int, const int, const int, const int, int, int, float *)
          detected during instantiation of "void caffe::im2col_gpu(const Dtype *, int, int, int, int, int, int, int, int, int, int, int, Dtype *) [with Dtype=float]" 
(65): here
Can you help me?

P.S. See files in attachment
[im2col_cu.txt](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/files/975737/im2col_cu.txt)
[im2col_cu_diff.txt](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/files/975738/im2col_cu_diff.txt)

**Comment by adityaatluri** [comment]
Hi,
HIP is not drop in replacement to make CUDA code run on AMD GPUs. You need to change names of work items, kernel signatures and use hipLaunchKernel to launch kernels.
I recommend reading https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md

The attached code is an incomplete port.

**Comment by sunway513** [comment]
Also, our port of Caffe has been released, please check it out:
https://github.com/ROCmSoftwarePlatform/hipCaffe

**Comment by adityaatluri** [comment]
Inactive
