### ISSUE TITLE
consider (possibly optional) lexical translation of cuda to HIP 

### ISSUE THREAD

**Issue by hgaspar** [GPUOpen-ProfessionalCompute-Tools/HIP#8]
For example, sometimes people have functions that use the word cuda, such as initCuda(). Or even in comments etc...

**Comment by adityaatluri** [comment]
Hi,
hipify translates only CUDA API functions. Such as cudaMalloc, cudaMemcpy etc., User specific function calls are not translated.

**Comment by bensander** [comment]
Actually the hipify tool performs a straight text transformation for a list of CUDA APIs, types, and enumerations - you can see the source in bin/hipify.  This would tranform commented out code or strings that match the transformation list but would not transform unlisted, general uses of the word "cuda" such as "initCuda".   We have seen this works quite well for many real application - but are are looking at developing a CLANG-based translation tool to further improve the robustness of the translation.

**Comment by adityaatluri** [comment]
Closing this issue. If you have more questions feel free to reopen it.
